import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { ArrowRight, BarChart3, Check, CircleAlert, Clock3, Eye, EyeOff, ExternalLink, Filter, KeyRound, LoaderCircle, LogOut, Menu, Search, Sparkles, Star, ThumbsUp, X } from 'lucide-react'
import api from './api'
import './styles.css'

const categories = ['All', 'UI/UX', 'Bugs/Performance', 'Pricing', 'Feature Request']
const getError = (error) => error.response?.data?.detail || error.message || 'Something went wrong.'
const isAuthed = () => Boolean(localStorage.getItem('access'))

function AuthPage({ mode }) {
  const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const signup = mode === 'signup'
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { const { data } = await api.post(`/api/auth/${signup ? 'signup' : 'login'}/`, { email, password }); localStorage.setItem('access', data.access); localStorage.setItem('refresh', data.refresh); navigate('/dashboard') } catch (err) { setError(getError(err)) } finally { setLoading(false) } }
  return <main className="auth-shell"><div className="auth-art"><div className="brand-mark">S</div><p className="eyebrow">SIGNAL / REVIEW INTELLIGENCE</p><h1>Find the story hiding inside the stars.</h1><p className="muted-copy">Live player feedback, sharpened into decisions your product team can act on.</p><div className="art-note"><Sparkles size={16} /> Google Play + Gemini 2.5 Flash</div></div><div className="auth-panel"><div className="auth-nav"><span className="wordmark">Signal<span>/</span></span><span className="muted-copy">{signup ? 'Already a member?' : 'New here?'} <button className="text-link" onClick={() => navigate(signup ? '/login' : '/signup')}>{signup ? 'Log in' : 'Create account'}</button></span></div><div className="form-wrap"><p className="eyebrow">{signup ? 'CREATE YOUR WORKSPACE' : 'WELCOME BACK'}</p><h2>{signup ? 'Build your feedback loop.' : 'Your signals are waiting.'}</h2><p className="muted-copy">{signup ? 'A free workspace for live review intelligence.' : 'Log in to see the latest pulse from your apps.'}</p><form onSubmit={submit} className="stack-form"><label>Email<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@company.com" /></label><label>Password<div className="password-field"><input type={showPassword ? 'text' : 'password'} required minLength="8" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="8 characters minimum" /><button type="button" className="password-toggle" onClick={() => setShowPassword((visible) => !visible)} aria-label={showPassword ? 'Conceal password' : 'Reveal password'} aria-pressed={showPassword}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>{error && <div className="error-box"><CircleAlert size={16} />{error}</div>}<button className="primary-button" disabled={loading}>{loading ? <LoaderCircle className="spin" size={17} /> : signup ? <KeyRound size={17} /> : <ArrowRight size={17} />}{loading ? 'Working...' : signup ? 'Create workspace' : 'Enter dashboard'}</button></form></div></div></main>
}

function AppShell({ children, apps, selectedId, onSelect, onLogout, onScrape, scraping }) {
  const [input, setInput] = useState(''); const [count, setCount] = useState(30); const [sidebar, setSidebar] = useState(false); const [error, setError] = useState('')
  async function submit(event) { event.preventDefault(); setError(''); try { const created = await onScrape(input, count); setInput(''); onSelect(created.id) } catch (err) { setError(getError(err)) } }
  return <div className="app-shell"><aside className={sidebar ? 'sidebar open' : 'sidebar'}><div className="sidebar-top"><div className="brand-mark small">S</div><span className="wordmark">Signal<span>/</span></span><button className="icon-button mobile-only" onClick={() => setSidebar(false)}><X size={18} /></button></div><div className="sidebar-label">YOUR APPS</div><div className="app-history">{apps.length ? apps.map((app) => <button key={app.id} className={selectedId === app.id ? 'history-item active' : 'history-item'} onClick={() => { onSelect(app.id); setSidebar(false) }}><img src={app.icon_url} alt="" /><span><strong>{app.title}</strong><small>{app.package_id}</small></span></button>) : <p className="empty-history">Your scraped apps will appear here.</p>}</div><div className="sidebar-bottom"><button className="logout-button" onClick={onLogout}><LogOut size={16} /> Log out</button></div></aside><main className="workspace"><header className="topbar"><button className="icon-button mobile-only" onClick={() => setSidebar(true)}><Menu size={20} /></button><div><p className="eyebrow">APP REVIEW INTELLIGENCE</p><h1>Make feedback useful.</h1></div><form className="scrape-form" onSubmit={submit}><Search size={17} /><input value={input} onChange={(e) => setInput(e.target.value)} required placeholder="Paste Play Store URL or package ID" /><label className="count-input"><span>Reviews</span><input type="number" min="1" max="300" value={count} onChange={(e) => setCount(Math.max(1, Math.min(300, Number(e.target.value) || 1)))} /></label><button disabled={scraping}>{scraping ? <LoaderCircle className="spin" size={17} /> : <ArrowRight size={17} />}</button></form></header>{error && <div className="global-error"><CircleAlert size={16} />{error}</div>}{scraping && <div className="progress-strip"><LoaderCircle className="spin" size={16} /> Scraping reviews <span>→</span> Running AI extraction <span>→</span> Saving to database</div>}{children}</main></div>
}

function ReviewCard({ review, positive }) { return <article className={`review-card ${positive ? 'love-card' : 'issue-card'}`}><div className="review-head"><div><div className="stars">{[1,2,3,4,5].map((n) => <Star key={n} size={14} fill={n <= (review.rating ?? review.score) ? 'currentColor' : 'none'} />)}</div><strong>{review.user_name || 'Anonymous reviewer'}</strong></div><span className="helpful"><ThumbsUp size={13} /> {review.thumbs_up ?? review.thumbs_up_count ?? 0}</span></div><p className="review-content">{review.content}</p>{review.extracted_issue && <div className="insight"><Sparkles size={14} /><span>{review.extracted_issue}</span></div>}<div className="review-foot"><span className="tag">{review.category}</span>{review.version && <span>v{review.version}</span>}{!review.ai_processed && <span>Heuristic analysis</span>}</div></article> }

function AnalysisBoard({ app, apps, onScrape }) { const [reviews, setReviews] = useState([]); const [category, setCategory] = useState('All'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState('')
  useEffect(() => { if (!app) return; setLoading(true); const params = category !== 'All' ? { category } : {}; api.get(`/api/apps/${app.id}/reviews/`, { params }).then(({ data }) => setReviews(data)).catch((err) => setError(getError(err))).finally(() => setLoading(false)) }, [app, category])
  if (!app) return <div className="welcome-state"><div className="welcome-icon"><BarChart3 size={28} /></div><p className="eyebrow">YOUR INTELLIGENCE DESK</p><h2>Choose an app to begin.</h2><p className="muted-copy">Paste a Google Play package ID above to fetch real reviews and let Gemini pull out the signal.</p></div>
  const filtered = reviews.filter((review) => review.content.toLowerCase().includes(query.toLowerCase())); const love = filtered.filter((r) => r.sentiment === 'positive'); const issues = filtered.filter((r) => r.sentiment === 'negative')
  return <section className="board"><div className="app-banner"><div className="app-identity"><img src={app.icon_url} alt="" /><div><p className="eyebrow">{app.developer}</p><h2>{app.title}</h2><p className="muted-copy">{app.package_id} · {app.review_count} useful reviews analyzed</p></div></div><a href={app.store_url} target="_blank" rel="noreferrer" className="outline-button">Play Store <ExternalLink size={15} /></a></div><div className="toolbar"><div className="filter-pills">{categories.map((item) => <button className={category === item ? 'pill active' : 'pill'} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><label className="filter-search"><Filter size={15} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search insights" /></label></div>{error && <div className="error-box"><CircleAlert size={16} />{error}</div>}{loading ? <div className="loading-state"><LoaderCircle className="spin" size={23} /> Loading analyzed reviews...</div> : <div className="split-board"><div className="column"><div className="column-heading love-heading"><div><span className="column-kicker">THE UPSIDE</span><h3>What people love</h3></div><span className="count-badge">{love.length}</span></div>{love.length ? love.map((review) => <ReviewCard key={review.review_id} review={review} positive />) : <p className="column-empty">No positive insights match this view.</p>}</div><div className="column"><div className="column-heading issue-heading"><div><span className="column-kicker">THE FRICTION</span><h3>What went wrong</h3></div><span className="count-badge">{issues.length}</span></div>{issues.length ? issues.map((review) => <ReviewCard key={review.review_id} review={review} />) : <p className="column-empty">No negative insights match this view.</p>}</div></div>}</section>
}

function Dashboard() { const navigate = useNavigate(); const [apps, setApps] = useState([]); const [selectedId, setSelectedId] = useState(null); const [scraping, setScraping] = useState(false); useEffect(() => { api.get('/api/apps/').then(({ data }) => { setApps(data); if (data[0]) setSelectedId(data[0].id) }).catch(() => { localStorage.clear(); navigate('/login') }) }, [navigate]); async function scrape(input, count) { setScraping(true); try { const { data } = await api.post('/api/apps/scrape/', { app_input: input, count }); setApps((current) => [data, ...current.filter((item) => item.id !== data.id)]); return data } finally { setScraping(false) } } function logout() { localStorage.clear(); navigate('/login') } return <AppShell apps={apps} selectedId={selectedId} onSelect={setSelectedId} onLogout={logout} onScrape={scrape} scraping={scraping}><AnalysisBoard app={apps.find((item) => item.id === selectedId)} apps={apps} onScrape={scrape} /></AppShell> }

function RequireAuth({ children }) { return isAuthed() ? children : <Navigate to="/login" replace /> }
function App() { return <Routes><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/signup" element={<AuthPage mode="signup" />} /><Route path="/dashboard" element={<RequireAuth><Dashboard /></RequireAuth>} /><Route path="*" element={<Navigate to={isAuthed() ? '/dashboard' : '/login'} replace />} /></Routes> }
createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>)
